### ISSUE TITLE
Simple todo list

### ISSUE THREAD

**Issue by mnelson4** [mnelson4/printmyblog#86]
* [x] designs declare nesting levels (eg "sections", "parts and sections", "parts, sections, and sub-sections", "books, parts, sections and sub-sections")
* [x] determine when to use start and stop templates
* [x] determine which template to use
* [x] refactor away from using `PartFetcher`
* [x] add shortcodes `pmb_title`, `pmb_toc`
* [x] debug generating: no main, no article
* [x] store section height from JS for use in PHP
* [x] auto-detect design level support (based on files)
* [x] have separate inputs for frontmatter and backmatter, and save them
* [x] have default sections (usually title and toc pages)
* [x] expose how many levels are available for a design/project
* [x] add button for quick adding project content
* [x] facilitate dragging
* [x] facilitate subfoldering
* [x] add delete and view buttons to project editor

**Comment by mnelson4** [comment]
Created new issue #87 for remaining items which I might not do
